# Generated by Django 4.2.7 on 2025-04-21 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projecttickets_backend_tasks_and_more'),
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('repo_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_projects', to='projects.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='codeexecution',
            name='project',
        ),
        migrations.AlterUniqueTogether(
            name='codefile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='codefile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='codefileversion',
            name='file',
        ),
        migrations.RemoveField(
            model_name='codeproject',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='toolcall',
            name='message',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='CodeExecution',
        ),
        migrations.DeleteModel(
            name='CodeFile',
        ),
        migrations.DeleteModel(
            name='CodeFileVersion',
        ),
        migrations.DeleteModel(
            name='CodeProject',
        ),
        migrations.DeleteModel(
            name='ToolCall',
        ),
        migrations.AddField(
            model_name='gitfile',
            name='git_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='coding.gitproject'),
        ),
        migrations.AddField(
            model_name='gitcommit',
            name='git_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='coding.gitproject'),
        ),
    ]
