# Generated by Django 4.2.7 on 2025-04-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_gitcommit_gitfile_gitproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitfile',
            name='git_project',
        ),
        migrations.RemoveField(
            model_name='gitproject',
            name='project',
        ),
        migrations.DeleteModel(
            name='GitCommit',
        ),
        migrations.DeleteModel(
            name='GitFile',
        ),
        migrations.DeleteModel(
            name='GitProject',
        ),
    ]
