# Generated by Django 4.2.7 on 2025-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '0003_remove_gitfile_git_project_remove_gitproject_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, help_text='Project identifier associated with this sandbox', max_length=255, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='Conversation identifier associated with this sandbox', max_length=255, null=True)),
                ('container_id', models.CharField(help_text='Docker container ID', max_length=255)),
                ('container_name', models.CharField(help_text='Docker container name', max_length=255)),
                ('image', models.CharField(help_text='Docker image used', max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='Port mapped for the container', null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='created', help_text='Current status of the sandbox', max_length=20)),
                ('resource_limits', models.JSONField(blank=True, help_text='Resource limits applied to the container', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the sandbox was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the sandbox was last updated')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the sandbox was started', null=True)),
                ('stopped_at', models.DateTimeField(blank=True, help_text='When the sandbox was stopped', null=True)),
            ],
            options={
                'verbose_name': 'Docker Sandbox',
                'verbose_name_plural': 'Docker Sandboxes',
                'indexes': [models.Index(fields=['project_id'], name='coding_dock_project_3755a1_idx'), models.Index(fields=['conversation_id'], name='coding_dock_convers_d45f8a_idx'), models.Index(fields=['container_id'], name='coding_dock_contain_2cb4be_idx'), models.Index(fields=['status'], name='coding_dock_status_0a6455_idx')],
            },
        ),
    ]
