# Generated by Django 4.2.7 on 2025-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockersandbox',
            name='code_dir',
            field=models.CharField(blank=True, help_text='Directory containing the code for this sandbox', max_length=512, null=True),
        ),
    ]
