# Generated by Django 4.2.7 on 2025-04-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_dockersandbox_code_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerPortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_port', models.IntegerField(help_text='Port number inside the container')),
                ('host_port', models.IntegerField(help_text='Port number on the host machine mapped to the container port')),
                ('command', models.CharField(blank=True, help_text='Command associated with this port (e.g., service running on this port)', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the port mapping was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the port mapping was last updated')),
                ('sandbox', models.ForeignKey(help_text='Docker sandbox this port mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='port_mappings', to='coding.dockersandbox')),
            ],
            options={
                'verbose_name': 'Docker Port Mapping',
                'verbose_name_plural': 'Docker Port Mappings',
                'indexes': [models.Index(fields=['sandbox'], name='coding_dock_sandbox_2aeba8_idx'), models.Index(fields=['container_port'], name='coding_dock_contain_4d80c4_idx'), models.Index(fields=['host_port'], name='coding_dock_host_po_a9160d_idx')],
                'unique_together': {('sandbox', 'host_port'), ('sandbox', 'container_port')},
            },
        ),
    ]
