# Generated by Django 4.2.7 on 2025-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_dockerportmapping'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dockersandbox',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_id__isnull', True)), fields=('project_id',), name='unique_project_sandbox'),
        ),
        migrations.AddConstraint(
            model_name='dockersandbox',
            constraint=models.UniqueConstraint(condition=models.Q(('project_id__isnull', True)), fields=('conversation_id',), name='unique_conversation_sandbox'),
        ),
        migrations.AddConstraint(
            model_name='dockersandbox',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_id__isnull', False), ('project_id__isnull', False)), fields=('project_id', 'conversation_id'), name='unique_project_conversation_sandbox'),
        ),
    ]
