# Generated by Django 4.2.7 on 2025-04-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_dockersandbox_unique_project_sandbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockersandbox',
            name='port',
        ),
    ]
