# Generated by Django 4.2.7 on 2025-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_remove_dockersandbox_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesPod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, help_text='Project identifier associated with this pod', max_length=255, null=True)),
                ('conversation_id', models.CharField(blank=True, help_text='Conversation identifier associated with this pod', max_length=255, null=True)),
                ('pod_name', models.CharField(help_text='Kubernetes pod name', max_length=255)),
                ('namespace', models.CharField(help_text='Kubernetes namespace', max_length=255)),
                ('image', models.CharField(help_text='Container image used', max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='created', help_text='Current status of the pod', max_length=20)),
                ('resource_limits', models.JSONField(blank=True, help_text='Resource limits applied to the pod', null=True)),
                ('service_details', models.JSONField(blank=True, help_text='Details of the associated services (ports, node ports, etc.)', null=True)),
                ('ssh_connection_details', models.JSONField(blank=True, help_text='SSH connection details for the k8s host server', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the pod was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the pod was last updated')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the pod was started', null=True)),
                ('stopped_at', models.DateTimeField(blank=True, help_text='When the pod was stopped', null=True)),
            ],
            options={
                'verbose_name': 'Kubernetes Pod',
                'verbose_name_plural': 'Kubernetes Pods',
                'indexes': [models.Index(fields=['project_id'], name='coding_kube_project_f5e7cd_idx'), models.Index(fields=['conversation_id'], name='coding_kube_convers_8587f7_idx'), models.Index(fields=['pod_name'], name='coding_kube_pod_nam_214c1f_idx'), models.Index(fields=['namespace'], name='coding_kube_namespa_283f9f_idx'), models.Index(fields=['status'], name='coding_kube_status_0e403e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='kubernetespod',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_id__isnull', True)), fields=('project_id',), name='unique_project_pod'),
        ),
        migrations.AddConstraint(
            model_name='kubernetespod',
            constraint=models.UniqueConstraint(condition=models.Q(('project_id__isnull', True)), fields=('conversation_id',), name='unique_conversation_pod'),
        ),
        migrations.AddConstraint(
            model_name='kubernetespod',
            constraint=models.UniqueConstraint(condition=models.Q(('conversation_id__isnull', False), ('project_id__isnull', False)), fields=('project_id', 'conversation_id'), name='unique_project_conversation_pod'),
        ),
    ]
