# Generated by Django 4.2.7 on 2025-05-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0009_kubernetespod_kubernetespod_unique_project_pod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetespod',
            name='cluster_host',
            field=models.CharField(blank=True, help_text='Kubernetes cluster API server host', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kubernetespod',
            name='kubeconfig',
            field=models.JSONField(blank=True, help_text='Kubernetes config as JSON for direct API access', null=True),
        ),
        migrations.AddField(
            model_name='kubernetespod',
            name='token',
            field=models.TextField(blank=True, help_text='Kubernetes API token for authentication', null=True),
        ),
    ]
