# Generated by Django 4.2.7 on 2025-05-06 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0010_kubernetespod_cluster_host_kubernetespod_kubeconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesPortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(help_text='Name of the container within the pod', max_length=255)),
                ('container_port', models.IntegerField(help_text='Port number inside the container')),
                ('service_port', models.IntegerField(help_text='Port number on the Kubernetes service')),
                ('node_port', models.IntegerField(blank=True, help_text='NodePort value if exposed via NodePort service type', null=True)),
                ('protocol', models.CharField(default='TCP', help_text='Protocol for this port (TCP, UDP)', max_length=10)),
                ('service_name', models.CharField(help_text='Name of the service exposing this port', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Description of the service running on this port', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the port mapping was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the port mapping was last updated')),
                ('pod', models.ForeignKey(help_text='Kubernetes pod this port mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='port_mappings', to='coding.kubernetespod')),
            ],
            options={
                'verbose_name': 'Kubernetes Port Mapping',
                'verbose_name_plural': 'Kubernetes Port Mappings',
                'indexes': [models.Index(fields=['pod'], name='coding_kube_pod_id_2a1fa3_idx'), models.Index(fields=['container_name'], name='coding_kube_contain_5810c6_idx'), models.Index(fields=['service_name'], name='coding_kube_service_1fb248_idx'), models.Index(fields=['container_port'], name='coding_kube_contain_e10f86_idx')],
                'unique_together': {('pod', 'container_name', 'container_port')},
            },
        ),
    ]
