# Generated by Django 4.2.7 on 2025-05-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0011_kubernetesportmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('command', models.TextField(help_text='The command that was executed')),
                ('output', models.TextField(blank=True, help_text='Output from the command', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
