# Generated by Django 5.1.6 on 2025-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sidebar_collapsed',
            field=models.BooleanField(default=False),
        ),
    ]
