# Generated by Django 4.2.7 on 2025-03-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conversations',
            field=models.ManyToManyField(blank=True, related_name='projects', to='chat.conversation'),
        ),
    ]
