# Generated by Django 4.2.7 on 2025-04-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_conversations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='conversations',
        ),
    ]
