# Generated by Django 4.2.7 on 2025-04-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectprd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprd',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prd', to='projects.project'),
        ),
    ]
