# Generated by Django 4.2.7 on 2025-04-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_conversations'),
        ('chat', '0002_conversation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_conversations', to='projects.project'),
        ),
    ]
