# Generated by Django 4.2.7 on 2025-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatfile_delete_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_if_file',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
