# Generated by Django 4.2.7 on 2025-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_content_if_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_if_file',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
