# Generated by Django 4.2.7 on 2025-05-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_content_if_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_role',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
    ]
