# Generated by Django 4.2.7 on 2025-05-22 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_message_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('product_analyst', 'Product Analyst'), ('default', 'Default')], default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
