# Generated by Django 4.2.7 on 2025-05-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_agentrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrole',
            name='name',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('product_analyst', 'Analyst'), ('default', 'Default')], default='product_analyst', max_length=50),
        ),
    ]
