# Generated by Django 4.2.7 on 2025-05-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_githubtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubtoken',
            name='github_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='githubtoken',
            name='github_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='githubtoken',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='githubtoken',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
