# Generated by Django 4.2.7 on 2025-05-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_githubtoken_github_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
