# Generated by Django 4.2.7 on 2025-04-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercredit',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usercredit',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
